### ISSUE TITLE
The letter p doesn't work on the FredokaOne font

### ISSUE THREAD

**Issue by G-Pereira** [VedantParanjape/KiBuzzard#14] opened 2021-04-06 23:30 UTC
![Screenshot from 2021-04-07 00-29-00](https://user-images.githubusercontent.com/15521303/113790086-76adda80-9738-11eb-9d37-4e8771ef1128.png)
![Screenshot from 2021-04-07 00-29-19](https://user-images.githubusercontent.com/15521303/113790090-77df0780-9738-11eb-96e0-ccdb65eeab16.png)

**Comment by iharshadec** [comment] 2021-04-07 03:16
@G-Pereira Yes Buzzard has this limitation for small letters and specically goes up or down the line. So it's better to use CAPITAL letters. That's best work-around for now.

**Comment by G-Pereira** [comment] 2021-04-07 08:17
Ok, thank you!

**Comment by VedantParanjape** [comment] 2021-04-09 16:48
@G-Pereira Feels good that this is being used in big projects, If the issue is solved fell free to close it :)

**Comment by G-Pereira** [comment] 2021-04-09 22:10
It isn't solved in the sense that the issue is still there. I get it that it's not an issue related to the goals of this fork (bringing 5.1.9 compatibility) so I've left it for you guys to decide :wink: 
We are using it on our Index pick and place machine's motherboard it looks so neat! Thank you for your hard work! We can't really use KiCAD 6 (5.99) yet since we need stability and use a version that everyone has (latest stable)

**Comment by VedantParanjape** [comment] 2021-04-10 13:20
> It isn't solved in the sense that the issue is still there. I get it that it's not an issue related to the goals of this fork (bringing 5.1.9 compatibility) so I've left it for you guys to decide wink
> We are using it on our Index pick and place machine's motherboard it looks so neat! Thank you for your hard work! We can't really use KiCAD 6 (5.99) yet since we need stability and use a version that everyone has (latest stable)

Thanks for the kind words :)

You might want to try out greg's new version, he is trying to create a new version not based on Buzzard but using svg2mod, or You might want to create an issue on Buzzard's repo, as if they fix it there. I can actually import it here.

**Comment by VedantParanjape** [comment] 2021-04-12 04:08
@G-Pereira Can you use these settings, it renders `p` fine.

![Screenshot from 2021-04-12 09-37-46](https://user-images.githubusercontent.com/22630228/114339440-d52ceb80-9b72-11eb-9ede-be20bb86f499.png)

Also can you give a shoutout to KiBuzzard so that more users will know about this tool :)

**Comment by G-Pereira** [comment] 2021-04-12 07:57
Thanks, i went with other designation that doesn't include that letter :)

**Comment by VedantParanjape** [comment] 2021-04-12 11:16
> Thanks, i went with other designation that doesn't include that letter :)

Okay. I'll close this issue then.

**Closed as completed by VedantParanjape** 2021-04-12 11:16 UTC
